<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MangaView.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MangaView.Core\MangaView.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibHeif.Native.Runtime" Version="1.20.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="LibHeifSharp" Version="3.2.0" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.17.1" />
  </ItemGroup>
</Project>
